[target.'cfg(all(target_arch = "arm", target_os = "none"))']
linker = "flip-link"
runner = "probe-rs run --chip nRF52840_xxAA"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
KEYBOARD_TOML_PATH = { value = "keyboard.toml", relative = true }
